name: Build Conference Paper
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile conference paper
        uses: xu-cheng/latex-action@1.2.1
        with:
          working_directory: paper
          root_file: paper.tex
      
      - name: Publish paper PDF
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Conference Paper
          path: paper/paper.pdf
          

