name: Build Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
#       - name: Test
#         run: ls -la

      - name: Compile conference paper
        uses: xu-cheng/latex-action@v2
        with:
          working-directory: report
#           working_directory: report
          root_file: report.tex
      
#       - name: Publish report PDF
#         uses: actions/upload-artifact@v1.0.0
#         with:
#           name: Conference Paper
#           path: report/report.pdf
          
