name: Build Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
#       - name: Test
#         run: ls -la

      - name: Compile conference paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          working_directory: report
      
      - name: Publish report PDF
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Report Document
          path: report/report.pdf
          
